language: minimal
addons:
  apt:
    packages:
     - texlive
     - texlive-lang-german
     - texlive-latex-extra
script: bash build.sh
before_deploy: export TRAVIS_TAG=1.0
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: diplom.pdf
  skip_cleanup: true
